run-distr :
	./build/install/app/bin/app

run-help :
	./build/install/app/bin/app -h

run-install-dir :
	./gradlew installDist

build :
	./gradlew build

run :
	./gradlew run

checkstyle-main :
	./app/gradlew checkstyleMain

report:
	./gradlew jacocoTestReport

.PHONY: build